# Generated by Django 3.0.7 on 2020-06-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(default='https://rotula.net/<django.db.models.fields.CharField>'),
        ),
    ]
