# Generated by Django 3.0.7 on 2020-06-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumenes', '0002_auto_20200613_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(default='https://rotula.net', unique=True),
        ),
    ]
